language: python
cache: pip
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  # disable pypy until travis upgrades to at least pypy2.6 due to cryptography
  #- pypy
  # disable pypy3 until 3.3 compliance
  #- pypy3
env:
  - STORAGE_SAMPLES_DIR=Python/Storage
  - BATCH_SAMPLES_DIR=Python/Batch
install:
  - pip install -e $STORAGE_SAMPLES_DIR
  - pip install coveralls flake8 pytest pytest-cov requests_mock
script:
  - cd $STORAGE_SAMPLES_DIR
  - flake8 blobxfer.py test/test_blobxfer.py
  - PYTHONPATH=. py.test -l --cov-config ../.coveragerc --cov-report term-missing --cov blobxfer test/test_blobxfer.py
  - cd $BATCH_SAMPLES_DIR
  - flake8 . --statistics
after_success:
  - coveralls --rcfile=../.coveragerc --verbose

