language: python
cache: pip
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
  # disable pypy3 until 3.3 compliance
  #- pypy3
install:
  - pip install azure-servicemanagement-legacy
  - pip install azure-storage
  - pip install coveralls
  - pip install flake8
  - pip install pycrypto
  - pip install pytest-cov
  - pip install requests
  - pip install requests_mock
env:
  - TEST_DIR=Python/Storage
script:
  - cd $TEST_DIR
  - flake8 blobxfer.py
  - PYTHONPATH=. py.test --cov-config ../.coveragerc --cov-report term-missing --cov blobxfer test/test_blobxfer.py
after_success:
  - coveralls --rcfile=../.coveragerc --verbose

